//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlbumCreator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Constants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Constants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlbumCreator.Constants", typeof(Constants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddImageBtn {
            get {
                return ResourceManager.GetString("AddImageBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddPageBtn {
            get {
                return ResourceManager.GetString("AddPageBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album.
        /// </summary>
        public static string AlbumSectionTitle {
            get {
                return ResourceManager.GetString("AlbumSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biztos, hogy el akarod vetni az eddig album módosításait?.
        /// </summary>
        public static string ConfirmAlbumReset {
            get {
                return ResourceManager.GetString("ConfirmAlbumReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new.
        /// </summary>
        public static string CreateNewBtn {
            get {
                return ResourceManager.GetString("CreateNewBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba történt.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album fájlok (*.album)|*.album.
        /// </summary>
        public static string FileDialogFilter {
            get {
                return ResourceManager.GetString("FileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string ImageSectionTitle {
            get {
                return ResourceManager.GetString("ImageSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout1.
        /// </summary>
        public static string Layout1Btn {
            get {
                return ResourceManager.GetString("Layout1Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout2.
        /// </summary>
        public static string Layout2Btn {
            get {
                return ResourceManager.GetString("Layout2Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout3.
        /// </summary>
        public static string Layout3Btn {
            get {
                return ResourceManager.GetString("Layout3Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout4.
        /// </summary>
        public static string Layout4Btn {
            get {
                return ResourceManager.GetString("Layout4Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout5.
        /// </summary>
        public static string Layout5Btn {
            get {
                return ResourceManager.GetString("Layout5Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout6.
        /// </summary>
        public static string Layout6Btn {
            get {
                return ResourceManager.GetString("Layout6Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout7.
        /// </summary>
        public static string Layout7Btn {
            get {
                return ResourceManager.GetString("Layout7Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout.
        /// </summary>
        public static string LayoutSectionTitle {
            get {
                return ResourceManager.GetString("LayoutSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A választott mappában nincs kép!.
        /// </summary>
        public static string MissingImage {
            get {
                return ResourceManager.GetString("MissingImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move down.
        /// </summary>
        public static string MoveDownImageBtn {
            get {
                return ResourceManager.GetString("MoveDownImageBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move up.
        /// </summary>
        public static string MoveUpImageBtn {
            get {
                return ResourceManager.GetString("MoveUpImageBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string OpenBtn {
            get {
                return ResourceManager.GetString("OpenBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open folder.
        /// </summary>
        public static string OpenImageFolderBtn {
            get {
                return ResourceManager.GetString("OpenImageFolderBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string PageSectionTitle {
            get {
                return ResourceManager.GetString("PageSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oldalak.
        /// </summary>
        public static string PageTreeViewTitle {
            get {
                return ResourceManager.GetString("PageTreeViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string RemoveImageBtn {
            get {
                return ResourceManager.GetString("RemoveImageBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string RemovePageBtn {
            get {
                return ResourceManager.GetString("RemovePageBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveBtn {
            get {
                return ResourceManager.GetString("SaveBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album Creator v1.0.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
